# utils/pdf_export.py
"""
Export a professional PDF bar bending schedule.
Uses ReportLab to create landscape A4 tables with optional shape images,
signature block, and robust styling.
"""

import datetime
import json
import logging
from typing import List, Optional

from reportlab.lib.pagesizes import landscape, A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, PageBreak, Paragraph, Spacer, Image
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.graphics.shapes import Drawing

from shapes.definitions import default_shape_registry
from logic.calculator import calculate_weight   # returns (unit_wt, piece_weight)
from db.database import DatabaseManager
from config import DEFAULT_REBAR_GRADE

logger = logging.getLogger(__name__)

# ---------- Optional SVG -> ReportLab Drawing support ----------
try:
    from svglib.svglib import svg2rlg
    from reportlab.graphics import renderPDF
    HAS_SVGLIB = True
except ImportError:
    HAS_SVGLIB = False

try:
    from shapes.svg_render import generate_shape_svg
    HAS_SVG_RENDER = True
except ImportError:
    HAS_SVG_RENDER = False


def _svg_to_drawing(svg_string: str, max_width: float = 80, max_height: float = 50) -> Optional[Drawing]:
    """Convert an SVG string to a ReportLab Drawing object, scaled to fit the given bounds."""
    if not HAS_SVGLIB or not HAS_SVG_RENDER:
        return None
    try:
        drawing = svg2rlg(io.StringIO(svg_string))
        # Scale to fit within max_width x max_height
        scale_x = max_width / drawing.width if drawing.width > 0 else 1
        scale_y = max_height / drawing.height if drawing.height > 0 else 1
        scale = min(scale_x, scale_y)
        drawing.scale(scale, scale)
        drawing.width = drawing.width * scale
        drawing.height = drawing.height * scale
        return drawing
    except Exception as e:
        logger.debug("Could not convert SVG to Drawing: %s", e)
        return None


# ---------- Signature / footer callback ----------
def _add_signature_block(canvas, doc):
    """Draw a signature block at the bottom of every page."""
    canvas.saveState()
    page_width, page_height = landscape(A4)
    footer_y = 20 * mm
    left_margin = 10 * mm
    right_margin = 10 * mm

    canvas.setFont('Helvetica-Bold', 8)
    canvas.drawString(left_margin, footer_y, "Designed by: ____________________")
    canvas.drawString(left_margin + 80*mm, footer_y, "Checked by: ____________________")
    canvas.drawString(left_margin + 160*mm, footer_y, "Date: ____________________")

    canvas.setFont('Helvetica', 7)
    canvas.drawRightString(page_width - right_margin, footer_y - 4*mm,
                           f"Page {doc.page} | Generated by RebarAgent")
    canvas.restoreState()


def export_pdf(
    filepath: str,
    project_id: int,
    project_name: str,
    client_name: str = "",
    summary_data: Optional[List[List]] = None,
    include_shape_images: bool = True,
    db: Optional[DatabaseManager] = None
) -> None:
    """
    Generate a PDF file containing:
        - Project header
        - Summary table (if summary_data provided)
        - Detailed tables per listofer with optional shape images
        - Signature block on every page

    Parameters
    ----------
    filepath : str
    project_id : int
    project_name, client_name : str
    summary_data : list of list, optional
    include_shape_images : bool
        If True, inserts small SVG drawings of each shape into the table.
        Requires svglib and shapes.svg_render to be installed.
    db : DatabaseManager, optional
    """
    if db is None:
        from db.database import db as default_db
        db = default_db

    doc = SimpleDocTemplate(
        filepath,
        pagesize=landscape(A4),
        topMargin=15 * mm,
        bottomMargin=25 * mm,   # extra space for signature block
        leftMargin=10 * mm,
        rightMargin=10 * mm
    )
    elements = []
    styles = getSampleStyleSheet()

    # ---- Header ----
    title_style = ParagraphStyle('CustomTitle', parent=styles['h1'], fontSize=16, spaceAfter=6)
    elements.append(Paragraph(f"Bar Bending Schedule – {project_name}", title_style))
    elements.append(Paragraph(
        f"Client: {client_name}" if client_name else "Client: —", styles['Normal']
    ))
    elements.append(Paragraph(
        f"Date: {datetime.date.today().isoformat()}", styles['Normal']
    ))
    elements.append(Spacer(1, 10 * mm))

    # ---- Summary table ----
    if summary_data:
        try:
            summary_headers = [
                "Diameter", "Grade", "Total Wt (kg)", "Total Len (m)",
                "# Stock Bars", "Waste (m)", "Waste (%)"
            ]
            if summary_data and len(summary_data[0]) == len(summary_headers):
                elements.append(Paragraph("Summary & Analysis", styles['h2']))
                table_data = [summary_headers] + summary_data
                col_widths = [30*mm, 20*mm, 30*mm, 30*mm, 25*mm, 25*mm, 25*mm]
                summary_table = Table(table_data, colWidths=col_widths, repeatRows=1)
                summary_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a3e6b')),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f3f7')]),
                ]))
                elements.append(summary_table)
                elements.append(PageBreak())
        except Exception as e:
            logger.warning("Could not build summary table: %s", e)

    # ---- Listofer-wise details ----
    listofers = db.fetchall(
        "SELECT id, number, description FROM listofers WHERE project_id = ? ORDER BY number",
        (project_id,)
    )

    # Column definitions: if images are on, add an extra "Shape" column at the end
    detail_cols = [
        "Pos.", "Dia (mm)", "Grade", "Shape", "Dimensions (mm)", "Qty",
        "Cut Length (mm)", "Unit Wt (kg/m)", "Total Wt (kg)",
        "Location", "Element"
    ]
    if include_shape_images and HAS_SVG_RENDER:
        detail_cols.append("Img")   # small image column
        img_col_width = 35 * mm
    else:
        img_col_width = 0 * mm

    col_widths_detail = [
        15*mm, 15*mm, 15*mm, 35*mm, 45*mm, 10*mm,
        25*mm, 25*mm, 25*mm, 25*mm, 25*mm
    ]

    for lid, lnum, ldesc in listofers:
        rebars = db.fetchall(
            """SELECT pos, diameter, shape_name, dimensions, quantity,
                      location, element_type, grade
               FROM rebars WHERE listofer_id = ? ORDER BY pos""",
            (lid,)
        )
        if not rebars:
            continue

        elements.append(Paragraph(f"Listofer: {lnum} – {ldesc or ''}", styles['h2']))
        table_data = [detail_cols]

        for pos, dia, sname, dims_str, qty, loc, elem, grade in rebars:
            shape_def = default_shape_registry.get_shape_def(sname)
            if shape_def is None:
                logger.warning("Unknown shape '%s' for listofer %s, skipping.", sname, lnum)
                continue

            # Parse dimensions
            try:
                if dims_str and dims_str.startswith('{'):
                    dims = json.loads(dims_str)
                else:
                    dims = {}
                    if dims_str:
                        for part in dims_str.split(','):
                            if '=' in part:
                                k, v = part.split('=')
                                dims[k.strip()] = float(v.strip())
            except Exception:
                dims = {}

            # Calculate length using registry
            try:
                cut_len = default_shape_registry.calc_shape_length(sname, dims, dia)
            except Exception:
                logger.warning("Could not compute length for shape '%s'", sname)
                cut_len = 0.0

            unit_wt, _ = calculate_weight(dia, cut_len)
            total_wt = unit_wt * qty

            dims_display = ", ".join(f"{k}={v:.0f}" for k, v in dims.items())
            grade_display = grade if grade else DEFAULT_REBAR_GRADE

            row = [
                pos,
                dia,
                grade_display,
                sname,
                dims_display,
                qty,
                f"{cut_len:.0f}",
                f"{unit_wt:.3f}",
                f"{total_wt:.2f}",
                loc or "—",
                elem or "—"
            ]

            # Optional shape image
            if include_shape_images and HAS_SVG_RENDER:
                shape_code = sname.split(" - ")[0].strip() if " - " in sname else sname
                dims_json = json.dumps(dims)
                svg_str = generate_shape_svg(shape_code, dims_json, dia, width=100, height=70)
                drawing = _svg_to_drawing(svg_str, max_width=30*mm, max_height=25*mm)
                row.append(drawing if drawing else "N/A")

            table_data.append(row)

        # Build table with appropriate column widths
        final_widths = col_widths_detail[:]
        if include_shape_images and HAS_SVG_RENDER:
            final_widths.append(img_col_width)
        else:
            # Remove the last column header if no images
            if detail_cols[-1] == "Img":
                detail_cols.pop()
                table_data = [detail_cols] + [row[:-1] for row in table_data[1:]]  # rebuild without image column

        detail_table = Table(table_data, colWidths=final_widths, repeatRows=1)
        detail_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1a3e6b')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 7),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 4),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f5f7fa')]),
        ]))
        elements.append(detail_table)
        elements.append(PageBreak())

    # Build the document with signature on every page
    doc.build(elements, onFirstPage=_add_signature_block, onLaterPages=_add_signature_block)
    logger.info("PDF export to '%s' completed.", filepath)